name: helping_nexus
description: Helping Nexus App

publish_to: 'none'

version: 1.0.7+9


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Critical
  http: ^1.2.1
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^5.0.2
  google_fonts: ^6.2.1
  go_router: ^13.2.0

  # Can be replaced
  image_picker: ^1.0.7
  flutter_card_swiper: ^7.0.0

  # Google Icons
  font_awesome_flutter: ^10.1.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/logos/
    - assets/backgrounds/