name: app
description: Helping Nexus App

publish_to: 'none'

version: 1.0.7+9

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Critical
  http: ^0.13.4
  go_router: ^4.2.7
  flutter_secure_storage: ^5.0.2

  # Can be replaced

  # Google Icons
  font_awesome_flutter: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets: